name: universal_navigation
description: The navigation core for flutter apps. Allows to use bottom navigation and transfer some data between blocs and pages.
version: 0.8.1
homepage: https://github.com/NikitaMasev/flutter_universal_navigation

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.1.3
  rxdart: ^0.27.0

dev_dependencies:
  flutter_test:
    sdk: flutter

